networks:
  br0:
    external: true

# 默认密码：admin@example.com         changeme
services:
  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:2.11.1'
    container_name: nginxproxymanager
    restart: always
    environment:
      DB_MYSQL_HOST: ${NPM_DB_HOST}
      DB_MYSQL_PORT: ${NPM_DB_PORT}
      DB_MYSQL_USER: ${NPM_DB_USER}
      DB_MYSQL_PASSWORD: ${NPM_DB_PASSWORD}
      DB_MYSQL_NAME:  ${NPM_DB_NAME}
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${NPM_DATA_DIR}:/data
      - ${NPM_LETSENCRYPT_DIR}:/etc/letsencrypt
    networks:
      br0:
        ipv4_address: ${NPM_IP}