networks:
  br0:
    external: true
    
services:
  postgres:
    image: postgres:16.10
    container_name: postgres

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - OUTLINE_DB_USER=${OUTLINE_DB_USER}
      - OUTLINE_DB_PASSWORD=${OUTLINE_DB_PASSWORD}
      - OUTLINE_DB_NAME=${OUTLINE_DB_NAME}
      - GITEA_DB_USER=${GITEA_DB_USER}
      - GITEA_DB_PASSWD=${GITEA_DB_PASSWD}
      - GITEA_DB_NAME=${GITEA_DB_NAME}
      - FRESHRSS_DB_USER=${FRESHRSS_DB_USER}
      - FRESHRSS_DB_PASSWORD=${FRESHRSS_DB_PASSWORD}
      - FRESHRSS_DB_NAME=${FRESHRSS_DB_NAME}
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
    networks:
      br0:
        ipv4_address: ${POSTGRES_IP}
