networks:
  br0:
    external: true
    
services:
  postgres:
    image: postgres:16.10
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
    networks:
      br0:
        ipv4_address: ${POSTGRES_IP}
