#!/bin/bash
set -e

# 使用 psql 执行 SQL 命令来创建用户和数据库
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- 创建 Outline 用户和数据库
    CREATE USER $OUTLINE_DB_USER WITH PASSWORD '$OUTLINE_DB_PASSWORD';
    CREATE DATABASE $OUTLINE_DB_NAME OWNER $OUTLINE_DB_USER;

    -- 创建 Gitea 用户和数据库
    CREATE USER $GITEA_DB_USER WITH PASSWORD '$GITEA_DB_PASSWD';
    CREATE DATABASE $GITEA_DB_NAME OWNER $GITEA_DB_USER;
EOSQL
