networks:
  br0:
    external: true

services:
  https-portal:
    image: steveltn/https-portal:1
    container_name: https-portal
    restart: always
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: '${OUTLINE_DOMAIN_NAME} -> http://${OUTLINE_IP}:${OUTLINE_PORT},${AUTH_DOMAIN_NAME} -> http://${HYDRA_IP}:4444,${AUTH_UI_DOMAIN_NAME} -> http://${HYDRA_CONSENT_UI_IP}:3000,${KRATOS_UI_DOMAIN_NAME} -> http://${KRATOS_UI_IP}:4455'
      STAGE: 'production' # Or 'staging' for testing
      # FORCE_RENEW: 'true' # Uncomment to force renew certificates
    volumes:
      - ${HTTPS_PORTAL_DATA_DIR}:/var/lib/https-portal
    networks:
      br0:
        ipv4_address: ${HTTPS_PORTAL_IP} # You need to define this IP in your config.sh
