networks:
  br0:
    external: true

services:
  keycloak:
    image: keycloak/keycloak:26.4.1
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=${KC_DB}
      - KC_DB_URL_HOST=${KC_DB_URL_HOST}
      - KC_DB_URL_DATABASE=${KC_DB_URL_DATABASE}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KC_HOSTNAME=${KEYCLOAK_DOMAIN_NAME}
      # This proxy setting is needed so Keycloak generates correct URLs when behind a reverse proxy
      - KC_PROXY=edge
    ports:
      - "8080:8080"
    volumes:
      - ./realm-config.json:/opt/keycloak/data/import/realm.json
    command: start-dev
    networks:
      br0:
        ipv4_address: ${KEYCLOAK_IP}
    restart: always
