version: '3.9'
networks:
  br0:
    external: true

services:
  outline:
    container_name: outline
    image: docker.getoutline.com/outlinewiki/outline:latest
    env_file: ${OUTLINE_ENV_FILE}
    ports:
      - "3001:3000"
    volumes:
      - ${OUTLINE_DATA_DIR}:/var/lib/outline/data
    networks:
      br0:
        ipv4_address: ${OUTLINE_IP}
