version: '3.9'
networks:
  br0:
    external: true

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    command:
      [
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci',
      ]
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_GITEA_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    networks:
      br0:
        ipv4_address: ${MYSQL_IP}