networks:
  br0:
    external: true
    
services:
  redis:
    image: redis:7.2.4
    container_name: redis
    volumes:
      - ${REDIS_DATA_DIR}:/data
      - ${REDIS_LOG_DIR}:/logs
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    networks:
      br0:
        ipv4_address: ${REDIS_IP}