networks:
  br0:
    external: true
    
services:
  redis:
    image: redis:8.2.2
    container_name: redis
    volumes:
      - ${REDIS_DATA_DIR}:/data
      - ${REDIS_LOG_DIR}:/logs
    command: redis-server --requirepass ${REDIS_PASSWORD}

    networks:
      br0:
        ipv4_address: ${REDIS_IP}
